//! IMPORTANTE  EXTENSIÓN  DE GOOGLE CHROME "AXE" AYUDA   HA INSPECCIONAR EL SITIO WEB EN EL ENTORNO DE ACCESIBILIDAD YA SEA DESKTOP COMO MOVIL


//ACTUALMENTE ESTAMOS ESTABLECIENDO LAS CONSTANTES "NAVTOGGLE" COMO "NAVMENU"
const navToggle = document.querySelector(".nav-toggle");
const navMenu = document.querySelector(".nav-menu");
//POSTERIORMENTE ESTAMOS REALIZANDO QUE CUANDO HAGA CLICK EN "NAV TOGGLE" COSA QUE SIGNIFICA QUE SI NO ESTÁ AÑADE SINO LA ELIMINA
//=> SIGNIFICA REALIZAR UNA NUEVA FUNCIÓN
navToggle.addEventListener("click", () => {
  navMenu.classList.toggle("nav-menu_visible");
  // AHORA EN ESTA FUNCIÓN ESTAMOS DICIENDO QUE : SI TENEMOS LA CLASE EN EL NAV MENU "NAV-MENU_VISIBLE"
  // PUES PONERLE EL AREA LABEL "CERRAR MENU" SINO AGREGAREOS EL "ABRIR MENÚ"
  // AL FINAL EL UN SI PASARÁ ESTO... Y SINO EL OTRO CASO SERÍA....
  if (navMenu.classList.contains("nav-menu_visible")) {
    navToggle.setAttribute("aria-label", "Cerrar menú");
  } else {
    navToggle.setAttribute("aria-label", "Abrir menú");
  }
});


// NOSOTROS EN ESTE CASO ESTÁMOS LLAMANDO A LA FUNCIÓN
function myFunction() {
  // AHORA ESTAMOS ESTABLECIENDO QUE VAMOS HA REALIZAR UN EVENTO EN EL "BODY"
  var element = document.body;
  // Y POSTERIORMENTE REALIZAMOS LA ALTERACIÓN AL "DARK MODE" REGLA QUE SE ENCUENTRA EN EL CSS
  element.classList.toggle("dark-mode");
}


//NOSOTROS AHORA ESTAMOS CREANDO UNA CONSNTANTE DE BOTÓN (ES UN SLELECTOR DE CONSULTA)
// EN EL QUE QUEREMOS QUE LA FUNciónN SE AGREGE EN LOS BOTONES DE "DATA-CAROUSEL-BUTTON"
const buttons = document.querySelectorAll("[data-carousel-button]")
// AHORA ESTAMOS DICIENDO QUE POR CADA BOTÓN
buttons.forEach(button => {
  // EMPEZANDO CON AGREGARLE  EL VENTO AL RELIZAR CLICK ENCIMA
  button.addEventListener("click", () => {
    // ESTAMOS CREANDO UNA CONSTANTE DE DESPLAZAMIENTO "button.dataset.carouselButton" ESTO LO TENGO AGREGADO EN EL HTML
    // ESTAMOS EXPRESANDO "SI ESO ES IGUAL AL SIGUIENTE; ENTONCES QUREMOS QUE ME DEVUELVA EL VALOR 1 EN LO CONTRARIO DEVUELVEME EL VALOR NEGATIVO"
    // EN ESTE CASO LA IMAGEN "ANTERIOR" Y "POSTERIOR"
    const offset = button.dataset.carouselButton === "next" ? 1 : -1
    // NOSOTROS DESDE NUESTRA CONSTANTE BUTTON
    const slides = button
      // QUEREMOS OBTENER EL "PADRE MÁS CERCANO ES DECIR "DATA-CAROUSEL"" (COSA QUE SE ENCUENTRA EN NUESTRO HTML )
      .closest("[data-carousel]")
      //AQUÍ LO QUE ESTAMOS AGREGANDO ES  UN SELECTOR DE CONSULTA PARA PODER OBTENER LAS IMAGENES
      .querySelector("[data-slides]")
    // AL REALIZAR LAS CARACTERÍSTICAS ANTERIORES PODEMOS OBTENER LAS IMÁGENES
    // ESTAMOS DICIENDO QUE LA CONSTANTE "ACTIVESLIDE" ES = HA "SLIDES" EN LAS QUE QUIERO QUE SE ECNUENTREN EN "DATA ACTIVE" 
    const activeSlide = slides.querySelector("[data-active]")
    // AHORA NOSOTROS QUEREMOS OBTENER EL NUVEO ÍNDICE -- NOSOTROS TAMBIÉN ESTAMOS ESTABLECIENDO QUE NUESTRAS IMÁGENES SEAN LOS "HIJOS"
    // TAMBIEÉN AGREGAMOS LA MÁTRIZ "ACTIVESLIDE" Y TAMBIÉN EL DESPLAZAMIENTO QUE SERÁ NEGATIVO 1: -1
    let newIndex = [...slides.children].indexOf(activeSlide) + offset
    // NOSOTROS AHORA ESTAMOS ESTABLECIENDO UNOS PEQUEÑOS IF DE NUESTRO "NEW INDEX"
    // EN ESTE CASO VAMOS HA IR HACIA ATRÁS LAS IMAGENES HIJOS Y CABAR EN -1 QUE VA HACER EL ÍNDICE DE NUESTRO ÚLTIMO ELEMENTO
    if (newIndex < 0) newIndex = slides.children.length - 1
    //EN ESTE CASO NOSOTROS ESTAMOS AGREGANDO QUE SI HA PASADO DE LA ÚLTIMA DIAPOSITIVA QUEREMOS VOLVER A LA DIAPOSITIVA DEL PRINCIPIO "UNA IMAGEN EN NUESTRO CASO"
    if (newIndex >= slides.children.length) newIndex = 0
    // AHORA PODEMOS DECIR QUE  SLIDES.CHILDREN QUEREMOS OBTENER EL "NEWINDEX" Y TAMBIÉN ESTABLECER EL CONJUTO DE DATOS IGUAL A "TRUE"
    slides.children[newIndex].dataset.active = true
    // POR TERMIANR ESTO NOS AYUDA A "ELIMINAR LA IMAGEN ANTERIOR" Y POSTERIORMENTE QUE APAREZCA LA SIGUIENTE (PARA EL DESARROLLO DEL BUCLE)
    delete activeSlide.dataset.active
  })
})


// AHORA ESTAMOS ESTABLECIENDO UNA NUEVA CONSTANTE  PARA QUE EL BOTÓN PUEDA REEDIRIGIRSE ARRIBA DE LA PÁGINA GRACIAS AL SELECTOR QUE LE ESTAMOS ESTABLECIENDO #SUBIR
const btnScrollToTop = document.querySelector("#subir");
// POSTERIORMENTE ESTAMOS AGREGANDO  UN DETECTOR DE EVENTOS  AL REALIZAR "CLICK" EN EL BOTÓN
// !IMPORTANTE : NOSOTROS HEMOS ELEGIGO  LA "FUNCTION" EN VEZ DE  LA "FUNCIÓN DE FLECHA" YA QUE TENÍA PROBLEMAS DE COMPATIBILIDAD EN EL DESARROLLO
btnScrollToTop.addEventListener("click", function () {
  // AHORA NOSOTROS ESTAMOS ESTABLECIENDO LAS REGLAS QUE SE VA HA REALIZAR EN LA VENTANA. EN ESTE CASO SUBIR UN 50 DE LA PÁGINA
  window.scrollTo({
    top: 50,
    left: 0,
    // ESTE ES UN COMPORTAMIENTO EN EL QUE ESTAMOS DICIENDO QUE VAYA DE FORMA FLUIDA Y SUAVES ES DECIR QUE NO SUBA DE FORMA AREGSIVA
    behavior: "smooth"
  });
});